<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
	<BaseOutputPath>$(SolutionDir)\bin\</BaseOutputPath>
	<OutputPath>$(SolutionDir)\bin\</OutputPath>
	<AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
	<AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
	<UseCommonOutputDirectory>true</UseCommonOutputDirectory>
	<RootNamespace>Dal</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\DalFacade\DalFacade.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Config.cs">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Compile>
    <Compile Update="ConfigImplementation.cs">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Compile>
    <Compile Update="CourierImplementation.cs">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Compile>
    <Compile Update="DalXml.cs">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Compile>
    <Compile Update="DeliveryImplementation.cs">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Compile>
    <Compile Update="OrderImplementation.cs">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Compile>
  </ItemGroup>

</Project>
